version: '3.8'

services:
  app:
    image: syarifka/donation-app:latest
    container_name: laravel_app
    restart: always
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./storage:/var/www/storage
      - ./laravel.env:/var/www/.env
    depends_on:
      - db
    networks:
      - laravel_net

  db:
    image: mysql:5.7
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_DATABASE: laravel_donation
      MYSQL_USER: root
      MYSQL_PASSWORD: '@password09'
      MYSQL_ROOT_PASSWORD: '@password09'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_net

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: always
    ports:
      - "8888:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_net

volumes:
  db_data:

networks:
  laravel_net:
    driver: bridge
